### PR TITLE
Fix `Synced` decorator not adding `caller_is_syncadapter` parameter o…

### LINKED ISSUE #22: `Synced` Table doesn't apply `SyncParams` in all methods.
`uriParams` are only decorated in `insertOperation` but `SyncParams` should be applied in all other cases as well.

### PR DESCRIPTION
**Pull request by dmfs**
…n update and delete. Fixes #22

### CODE REVIEW

File: contentpal/src/test/java/org/dmfs/android/contentpal/tables/SyncedTest.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    public void testInsertOperation() throws Exception
+    {
+        final InsertOperation<Object> resultOperation = mock(InsertOperation.class);
+        Table<Object> testTable = new Synced<>(new AbstractMockTable()
+        {
+            @NonNull
+            @Override
+            public InsertOperation<Object> insertOperation(@NonNull UriParams uriParams)
+            {
+                // TODO: how do we check if any other params are still present?
```
Comment (lemonboston) [inline contentpal/src/test/java/org/dmfs/android/contentpal/tables/SyncedTest.java:57]: About how to check other params, simply preparing an UriParams at the beginning of the test and use that instead of `EmptyParams`, and assert for its content in `insertOperation`?

File: contentpal/src/test/java/org/dmfs/android/contentpal/tables/SyncedTest.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+ */
+@RunWith(RobolectricTestRunner.class)
+@Config(manifest = "src/test/AndroidManifest.xml")
+public class SyncedTest
+{
+    @Test
+    public void testInsertOperation() throws Exception
+    {
+        final InsertOperation<Object> resultOperation = mock(InsertOperation.class);
+        Table<Object> testTable = new Synced<>(new AbstractMockTable()
```
Comment (lemonboston) [inline contentpal/src/test/java/org/dmfs/android/contentpal/tables/SyncedTest.java:51]: Not sure if that was better but I looked it up how this could be handled with Mockito instead of this custom `AbstractMockTable`.
There is this that `ArgumentCaptor` but as they say here:
https://static.javadoc.io/org.mockito/mockito-core/2.2.9/org/mockito/ArgumentCaptor.html
it can make tests harder to read,
however there is this `ArgumentMather` which could be better:
https://static.javadoc.io/org.mockito/mockito-core/2.2.9/org/mockito/ArgumentMatcher.html
(mockito should be updated to 2.1 for this new interface)

Just mentioning, not suggesting that it should be changed now.

**Review by lemonboston — APPROVED** [review]
Looks good to me.
